"""Seed data for component definitions and DB-backed service functions.

SEED_COMPONENTS provides the initial data for the components table (used by
the Alembic migration and test fixtures). The service functions query the DB.
"""
from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..models.component import Component


SEED_COMPONENTS: list[dict] = [
    {"type": "file_loader", "category": "parser", "name": "File Loader", "description": "Loads documents from local file path (PDF, TXT, DOCX, CSV)", "config_schema": {"type": "object", "properties": {"file_path": {"type": "string", "description": "Path to the file or directory"}, "file_type": {"type": "string", "enum": ["pdf", "txt", "docx", "csv", "md", "epub", "html"], "description": "Type of file"}, "pdf_engine": {"type": "string", "enum": ["pymupdf", "pdfplumber", "unstructured", "docling"], "default": "pymupdf", "description": "PDF parsing engine"}, "ocr_enabled": {"type": "boolean", "default": False, "description": "Enable OCR for scanned documents"}, "ocr_language": {"type": "string", "default": "eng", "description": "Tesseract OCR language code"}, "extract_tables": {"type": "boolean", "default": True, "description": "Extract tables from documents"}, "extract_images": {"type": "boolean", "default": False, "description": "Extract images from documents"}, "encoding": {"type": "string", "default": "utf-8", "description": "File encoding"}, "max_file_size_mb": {"type": "integer", "default": 100, "minimum": 1, "maximum": 1000, "description": "Maximum file size in MB"}, "metadata_extraction": {"type": "boolean", "default": True, "description": "Extract document metadata (title, author, dates)"}}, "required": ["file_path"]}, "input_ports": [], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "multi_parser", "category": "parser", "name": "Multi-Format Parser", "description": "Parses multiple file formats: PDF, DOCX, Markdown, TXT, EPUB, HTML", "config_schema": {"type": "object", "properties": {"formats": {"type": "array", "items": {"type": "string"}, "default": ["pdf", "docx", "md", "txt", "epub", "html"], "description": "Supported file formats"}, "pdf_engine": {"type": "string", "enum": ["pymupdf", "pdfplumber", "unstructured", "docling"], "default": "pymupdf", "description": "PDF parsing engine"}, "ocr_enabled": {"type": "boolean", "default": False, "description": "Enable OCR for scanned documents"}, "extract_tables": {"type": "boolean", "default": True, "description": "Extract tables from documents"}, "metadata_extraction": {"type": "boolean", "default": True, "description": "Extract document metadata"}}}, "input_ports": [], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "web_scraper", "category": "parser", "name": "Web Scraper", "description": "Scrapes and parses content from web pages", "config_schema": {"type": "object", "properties": {"url": {"type": "string", "description": "URL to scrape"}, "css_selector": {"type": "string", "description": "CSS selector for content extraction"}, "wait_for_js": {"type": "boolean", "default": False, "description": "Wait for JavaScript rendering"}, "timeout_seconds": {"type": "integer", "default": 30, "minimum": 1, "maximum": 300, "description": "Request timeout in seconds"}}, "required": ["url"]}, "input_ports": [], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "recursive_chunker", "category": "chunker", "name": "Recursive Chunker", "description": "Hierarchical text splitting with multiple separator levels. Best general-purpose: 88-89% recall (Chroma 2024)", "config_schema": {"type": "object", "properties": {"chunk_size": {"type": "integer", "default": 512, "minimum": 64, "maximum": 8192, "description": "Target chunk size"}, "chunk_overlap": {"type": "integer", "default": 50, "minimum": 0, "maximum": 512, "description": "Overlap between chunks"}, "size_unit": {"type": "string", "enum": ["tokens", "characters", "words"], "default": "tokens", "description": "Unit for chunk_size and chunk_overlap"}, "separators": {"type": "array", "items": {"type": "string"}, "default": ["\n\n\n", "\n\n", "\n", ". ", " ", ""], "description": "Hierarchical separators from coarse to fine", "ui_advanced": True}, "min_chunk_size": {"type": "integer", "default": 50, "minimum": 0, "description": "Discard chunks smaller than this"}, "strip_whitespace": {"type": "boolean", "default": True, "description": "Strip whitespace from chunks"}, "add_metadata": {"type": "boolean", "default": True, "description": "Add chunker metadata to each chunk"}}}, "input_ports": [{"name": "documents", "type": "document_list"}], "output_ports": [{"name": "chunks", "type": "chunk_list"}]},
    {"type": "semantic_chunker", "category": "chunker", "name": "Semantic Chunker", "description": "Splits text at natural semantic boundaries using embedding similarity. Highest recall: 91% (Chroma 2024)", "config_schema": {"type": "object", "properties": {"chunk_size": {"type": "integer", "default": 512, "minimum": 64, "maximum": 8192, "description": "Target chunk size"}, "similarity_threshold": {"type": "number", "default": 0.8, "minimum": 0.0, "maximum": 1.0, "description": "Cosine similarity threshold for boundary detection"}, "breakpoint_type": {"type": "string", "enum": ["percentile", "stddev", "interquartile"], "default": "percentile", "description": "Boundary detection method"}, "breakpoint_value": {"type": "number", "default": 95.0, "description": "Breakpoint threshold (95th percentile, 2.0 stddev, etc.)"}, "embedding_model_for_chunking": {"type": "string", "default": "all-MiniLM-L6-v2", "description": "Embedding model for similarity computation"}, "buffer_size": {"type": "integer", "default": 1, "minimum": 0, "maximum": 5, "description": "Sentences of context around boundary", "ui_advanced": True}, "min_chunk_size": {"type": "integer", "default": 50, "minimum": 0, "description": "Discard chunks smaller than this"}}}, "input_ports": [{"name": "documents", "type": "document_list"}], "output_ports": [{"name": "chunks", "type": "chunk_list"}]},
    {"type": "token_chunker", "category": "chunker", "name": "Token Chunker", "description": "Splits documents into precise token-based chunks using tiktoken", "config_schema": {"type": "object", "properties": {"chunk_size": {"type": "integer", "default": 512, "minimum": 64, "maximum": 8192, "description": "Tokens per chunk"}, "chunk_overlap": {"type": "integer", "default": 50, "minimum": 0, "maximum": 512, "description": "Token overlap between chunks"}, "tokenizer": {"type": "string", "default": "cl100k_base", "description": "Tiktoken encoding name", "ui_advanced": True}}}, "input_ports": [{"name": "documents", "type": "document_list"}], "output_ports": [{"name": "chunks", "type": "chunk_list"}]},
    {"type": "sentence_chunker", "category": "chunker", "name": "Sentence Chunker", "description": "Splits text into sentence-level chunks with configurable grouping", "config_schema": {"type": "object", "properties": {"min_sentences": {"type": "integer", "default": 3, "minimum": 1, "description": "Minimum sentences per chunk"}, "max_sentences": {"type": "integer", "default": 10, "minimum": 1, "description": "Maximum sentences per chunk"}}}, "input_ports": [{"name": "documents", "type": "document_list"}], "output_ports": [{"name": "chunks", "type": "chunk_list"}]},
    {"type": "proposition_chunker", "category": "chunker", "name": "Proposition Chunker", "description": "Decomposes text into atomic self-contained propositions. +10 Recall@20 (Dense X, arXiv:2312.06648)", "config_schema": {"type": "object", "properties": {"proposition_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for proposition decomposition"}, "decontextualize": {"type": "boolean", "default": True, "description": "Resolve pronouns and add context for self-containment"}, "chunk_size": {"type": "integer", "default": 512, "minimum": 64, "maximum": 8192, "description": "Source passage size to decompose"}}}, "input_ports": [{"name": "documents", "type": "document_list"}], "output_ports": [{"name": "chunks", "type": "chunk_list"}]},
    {"type": "contextual_chunker", "category": "chunker", "name": "Contextual Chunker", "description": "Prepends LLM-generated context to each chunk. -49% retrieval failures (Anthropic 2024)", "config_schema": {"type": "object", "properties": {"chunk_size": {"type": "integer", "default": 512, "minimum": 64, "maximum": 8192, "description": "Target chunk size"}, "chunk_overlap": {"type": "integer", "default": 50, "minimum": 0, "maximum": 512, "description": "Overlap between chunks"}, "context_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for context generation"}, "context_prompt": {"type": "string", "default": "Situate this chunk within the overall document for search", "description": "Prompt for context enrichment", "ui_widget": "textarea"}}}, "input_ports": [{"name": "documents", "type": "document_list"}], "output_ports": [{"name": "chunks", "type": "chunk_list"}]},
    {"type": "hierarchical_chunker", "category": "chunker", "name": "Hierarchical Chunker", "description": "Small-to-Big: index small chunks for retrieval, expand to parent for LLM context", "config_schema": {"type": "object", "properties": {"child_chunk_size": {"type": "integer", "default": 128, "minimum": 32, "maximum": 2048, "description": "Small chunk size for retrieval"}, "parent_chunk_size": {"type": "integer", "default": 1024, "minimum": 128, "maximum": 8192, "description": "Large chunk size for LLM context"}, "expansion_strategy": {"type": "string", "enum": ["parent", "siblings", "window"], "default": "parent", "description": "How to expand retrieved child chunks"}}}, "input_ports": [{"name": "documents", "type": "document_list"}], "output_ports": [{"name": "chunks", "type": "chunk_list"}]},
    {"type": "document_structure_chunker", "category": "chunker", "name": "Document Structure Chunker", "description": "Structure-aware chunking respecting headers, tables, and code blocks", "config_schema": {"type": "object", "properties": {"chunk_size": {"type": "integer", "default": 512, "minimum": 64, "maximum": 8192, "description": "Target chunk size"}, "respect_headers": {"type": "boolean", "default": True, "description": "Split at document headings"}, "respect_tables": {"type": "boolean", "default": True, "description": "Keep tables as atomic chunks"}, "respect_code_blocks": {"type": "boolean", "default": True, "description": "Keep code blocks as atomic chunks"}, "header_patterns": {"type": "array", "items": {"type": "string"}, "default": ["^#{1,6}\\s", "^\\d+\\.\\s"], "description": "Regex patterns for detecting headings", "ui_advanced": True}, "attach_header_chain": {"type": "boolean", "default": True, "description": "Prepend parent heading hierarchy to each chunk"}}}, "input_ports": [{"name": "documents", "type": "document_list"}], "output_ports": [{"name": "chunks", "type": "chunk_list"}]},
    {"type": "openai_embedder", "category": "embedder", "name": "OpenAI Embedder", "description": "OpenAI text-embedding-3 models. Best cost-effective API. Matryoshka dimension support", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "text-embedding-3-small", "enum": ["text-embedding-3-small", "text-embedding-3-large", "text-embedding-ada-002"], "description": "OpenAI embedding model"}, "dimensions": {"type": "integer", "default": None, "description": "Output dimensions (None=default; set for Matryoshka truncation, e.g., 256, 512, 1024)"}, "batch_size": {"type": "integer", "default": 100, "minimum": 1, "maximum": 2048, "description": "Texts per API call"}, "max_retries": {"type": "integer", "default": 3, "minimum": 0, "description": "API retry attempts"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "embeddings", "type": "embedding_list"}]},
    {"type": "sentence_transformer_embedder", "category": "embedder", "name": "Sentence Transformer", "description": "Local embedding using sentence-transformers. Best small/fast: all-MiniLM-L6-v2", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "all-MiniLM-L6-v2", "description": "Sentence Transformer model name"}, "batch_size": {"type": "integer", "default": 64, "minimum": 1, "description": "Batch size"}, "device": {"type": "string", "enum": ["cpu", "cuda", "mps", "auto"], "default": "auto", "description": "Compute device"}, "normalize": {"type": "boolean", "default": True, "description": "L2-normalize embeddings"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "embeddings", "type": "embedding_list"}]},
    {"type": "e5_embedder", "category": "embedder", "name": "E5 Embedder", "description": "Microsoft E5 embeddings for cross-lingual retrieval. Requires instruction prefixes", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "intfloat/e5-large-v2", "description": "E5 model"}, "query_prefix": {"type": "string", "default": "query: ", "description": "Prefix for query texts"}, "document_prefix": {"type": "string", "default": "passage: ", "description": "Prefix for document texts"}, "batch_size": {"type": "integer", "default": 64, "minimum": 1, "description": "Batch size"}, "device": {"type": "string", "enum": ["cpu", "cuda", "mps", "auto"], "default": "auto", "description": "Compute device"}, "normalize": {"type": "boolean", "default": True, "description": "L2-normalize embeddings"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "embeddings", "type": "embedding_list"}]},
    {"type": "bge_m3_embedder", "category": "embedder", "name": "BGE-M3 Embedder", "description": "BAAI/bge-m3: dense + sparse + ColBERT simultaneously. 100+ languages. MIT license", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "BAAI/bge-m3", "description": "BGE-M3 model"}, "query_prefix": {"type": "string", "default": "Represent this sentence for searching relevant passages: ", "description": "Instruction prefix for queries"}, "output_modes": {"type": "array", "items": {"type": "string", "enum": ["dense", "sparse", "colbert"]}, "default": ["dense"], "description": "Embedding output modes (BGE-M3 supports all three simultaneously)"}, "batch_size": {"type": "integer", "default": 32, "minimum": 1, "description": "Batch size"}, "device": {"type": "string", "enum": ["cpu", "cuda", "mps", "auto"], "default": "auto", "description": "Compute device"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "embeddings", "type": "embedding_list"}]},
    {"type": "cohere_embedder", "category": "embedder", "name": "Cohere Embedder", "description": "Cohere embed-v4 with required input_type. Robust multilingual", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "embed-v4.0", "description": "Cohere embedding model"}, "input_type": {"type": "string", "enum": ["search_document", "search_query", "classification", "clustering"], "default": "search_document", "description": "Input type (REQUIRED for Cohere v3+)"}, "dimensions": {"type": "integer", "default": None, "description": "Output dimensions (Matryoshka: 256, 512, 768, 1024, 1536)"}, "batch_size": {"type": "integer", "default": 96, "minimum": 1, "maximum": 96, "description": "Batch size"}, "truncation_strategy": {"type": "string", "enum": ["NONE", "START", "END"], "default": "END", "description": "Text truncation strategy"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "embeddings", "type": "embedding_list"}]},
    {"type": "jina_embedder", "category": "embedder", "name": "Jina Embedder", "description": "Jina-embeddings-v3 with LoRA task adapters. 30+ languages (arXiv:2409.10173)", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "jinaai/jina-embeddings-v3", "description": "Jina embedding model"}, "task": {"type": "string", "enum": ["retrieval.query", "retrieval.passage", "separation", "classification", "text-matching"], "default": "retrieval.passage", "description": "LoRA task adapter (<3% params, specializes model)"}, "dimensions": {"type": "integer", "default": 1024, "description": "Output dimensions (Matryoshka: 32-1024)"}, "batch_size": {"type": "integer", "default": 32, "minimum": 1, "description": "Batch size"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "embeddings", "type": "embedding_list"}]},
    {"type": "nomic_embedder", "category": "embedder", "name": "Nomic Embedder", "description": "Nomic-embed-text-v2: first MoE embedding model. Apache 2.0", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "nomic-ai/nomic-embed-text-v1.5", "description": "Nomic model"}, "query_prefix": {"type": "string", "default": "search_query: ", "description": "Query prefix (required)"}, "document_prefix": {"type": "string", "default": "search_document: ", "description": "Document prefix (required)"}, "dimensions": {"type": "integer", "default": 768, "description": "Output dimensions (Matryoshka: 64-768)"}, "batch_size": {"type": "integer", "default": 64, "minimum": 1, "description": "Batch size"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "embeddings", "type": "embedding_list"}]},
    {"type": "voyage_embedder", "category": "embedder", "name": "Voyage Embedder", "description": "Voyage-3-large: best for domain-specific. Outperforms OpenAI by 9.74%", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "voyage-3-large", "description": "Voyage model"}, "input_type": {"type": "string", "enum": ["query", "document"], "default": "document", "description": "Input type"}, "dimensions": {"type": "integer", "default": 1024, "description": "Output dimensions (256-2048)"}, "batch_size": {"type": "integer", "default": 128, "minimum": 1, "description": "Batch size"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "embeddings", "type": "embedding_list"}]},
    {"type": "schema_free_extractor", "category": "extractor", "name": "Schema-Free Extractor", "description": "Open information extraction of entities and relations. Better recall (arXiv:2510.20345)", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for extraction"}, "entity_types": {"type": "array", "items": {"type": "string"}, "default": ["Person", "Organization", "Location", "Concept", "Event", "Technology"], "description": "Entity types to extract (empty=auto-detect)"}, "max_gleaning": {"type": "integer", "default": 1, "minimum": 0, "maximum": 5, "description": "Re-extraction passes for missed entities"}, "confidence_threshold": {"type": "number", "default": 0.5, "minimum": 0.0, "maximum": 1.0, "description": "Minimum confidence to keep"}, "resolve_coreferences": {"type": "boolean", "default": True, "description": "Resolve pronouns to referent entities"}, "merge_threshold": {"type": "number", "default": 0.85, "minimum": 0.0, "maximum": 1.0, "description": "Similarity threshold for merging duplicates"}, "batch_size": {"type": "integer", "default": 10, "minimum": 1, "description": "Chunks per extraction batch"}, "include_descriptions": {"type": "boolean", "default": True, "description": "Include entity/relation descriptions"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "entities", "type": "entity_list"}, {"name": "relations", "type": "relation_list"}]},
    {"type": "schema_constrained_extractor", "category": "extractor", "name": "Schema-Constrained Extractor", "description": "Extract entities/relations following a predefined domain schema. Better precision", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for extraction"}, "extraction_schema": {"type": "object", "description": "Domain ontology definition (entity types, relation types, constraints)"}, "entity_types": {"type": "array", "items": {"type": "string"}, "default": [], "description": "Allowed entity types"}, "relation_types": {"type": "array", "items": {"type": "string"}, "default": [], "description": "Allowed relation types"}, "max_gleaning": {"type": "integer", "default": 1, "minimum": 0, "maximum": 5, "description": "Re-extraction passes"}, "confidence_threshold": {"type": "number", "default": 0.5, "minimum": 0.0, "maximum": 1.0, "description": "Minimum confidence"}, "resolve_coreferences": {"type": "boolean", "default": True, "description": "Resolve coreferences"}, "batch_size": {"type": "integer", "default": 10, "minimum": 1, "description": "Chunks per batch"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "entities", "type": "entity_list"}, {"name": "relations", "type": "relation_list"}]},
    {"type": "entity_extractor", "category": "extractor", "name": "LightRAG Entity Extractor", "description": "Named entity extraction with types and descriptions (LightRAG-style gleaning)", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for extraction"}, "entity_types": {"type": "array", "items": {"type": "string"}, "default": ["Person", "Organization", "Location", "Concept"], "description": "Entity types to extract"}, "max_gleaning": {"type": "integer", "default": 1, "minimum": 0, "maximum": 5, "description": "Gleaning passes"}, "include_descriptions": {"type": "boolean", "default": True, "description": "Include descriptions"}, "include_source_spans": {"type": "boolean", "default": True, "description": "Include source text spans"}}}, "input_ports": [{"name": "chunks", "type": "chunk_list"}], "output_ports": [{"name": "entities", "type": "entity_list"}]},
    {"type": "subquery_decomposer", "category": "extractor", "name": "CoRAG Subquery Decomposer", "description": "Decompose complex queries into simpler sub-queries for multi-hop retrieval (CoRAG)", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for decomposition"}, "max_hops": {"type": "integer", "default": 3, "minimum": 1, "maximum": 10, "description": "Maximum sub-query hops"}, "reformulation_enabled": {"type": "boolean", "default": True, "description": "Allow query reformulation between hops"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "subqueries", "type": "string_list"}]},
    {"type": "lightrag_graph_builder", "category": "graph_builder", "name": "LightRAG Graph Builder", "description": "Build knowledge graph from entities and relations with entity resolution", "config_schema": {"type": "object", "properties": {"entity_resolution_mode": {"type": "string", "enum": ["exact", "fuzzy", "embedding", "llm", "hybrid"], "default": "embedding", "description": "Entity deduplication approach"}, "dedup_threshold": {"type": "number", "default": 0.85, "minimum": 0.0, "maximum": 1.0, "description": "Similarity threshold for entity merging"}, "merge_strategy": {"type": "string", "enum": ["merge_descriptions", "keep_latest", "keep_highest_score", "summarize"], "default": "merge_descriptions", "description": "How to merge duplicate entities"}, "add_chunk_links": {"type": "boolean", "default": True, "description": "Link chunks to extracted entities"}, "edge_weight_mode": {"type": "string", "enum": ["frequency", "confidence", "uniform"], "default": "frequency", "description": "Edge weight computation", "ui_advanced": True}, "incremental": {"type": "boolean", "default": True, "description": "Enable incremental graph updates"}}}, "input_ports": [{"name": "entities", "type": "entity_list"}, {"name": "relations", "type": "relation_list"}], "output_ports": [{"name": "graph", "type": "knowledge_graph"}]},
    {"type": "kag_subgraph_builder", "category": "graph_builder", "name": "KAG Subgraph Builder", "description": "Hierarchical knowledge subgraphs with community detection (GraphRAG-style)", "config_schema": {"type": "object", "properties": {"add_chunk_links": {"type": "boolean", "default": True, "description": "Link chunks to entities"}, "community_algorithm": {"type": "string", "enum": ["leiden", "louvain", "label_propagation", "none"], "default": "leiden", "description": "Community detection algorithm"}, "community_resolution": {"type": "number", "default": 1.0, "minimum": 0.1, "maximum": 10.0, "description": "Resolution (higher=smaller communities)"}, "min_community_size": {"type": "integer", "default": 5, "minimum": 2, "description": "Minimum nodes per community"}, "max_hierarchy_levels": {"type": "integer", "default": 3, "minimum": 1, "maximum": 10, "description": "Community hierarchy depth"}, "generate_community_summaries": {"type": "boolean", "default": True, "description": "Generate LLM summaries per community"}, "summary_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for community summaries"}}}, "input_ports": [{"name": "entities", "type": "entity_list"}, {"name": "relations", "type": "relation_list"}], "output_ports": [{"name": "subgraph", "type": "knowledge_graph"}]},
    {"type": "faiss_indexer", "category": "indexer", "name": "FAISS Indexer", "description": "Build FAISS vector index. HNSW M=16 gives 97-99% recall", "config_schema": {"type": "object", "properties": {"index_type": {"type": "string", "enum": ["flat", "ivf_flat", "ivf_pq", "hnsw"], "default": "hnsw", "description": "Index algorithm"}, "distance_metric": {"type": "string", "enum": ["cosine", "l2", "inner_product"], "default": "cosine", "description": "Distance metric"}, "dimension": {"type": "integer", "default": 1536, "minimum": 1, "description": "Embedding dimension"}, "hnsw_m": {"type": "integer", "default": 16, "minimum": 4, "maximum": 64, "description": "HNSW: max connections per node"}, "hnsw_ef_construction": {"type": "integer", "default": 128, "minimum": 16, "maximum": 512, "description": "HNSW: build-time search width"}, "hnsw_ef_search": {"type": "integer", "default": 64, "minimum": 16, "maximum": 512, "description": "HNSW: query-time search width"}, "nlist": {"type": "integer", "default": 1024, "minimum": 1, "description": "IVF: number of Voronoi cells"}, "nprobe": {"type": "integer", "default": 64, "minimum": 1, "description": "IVF: cells to probe at query time"}, "normalize_vectors": {"type": "boolean", "default": True, "description": "L2-normalize before indexing"}, "batch_size": {"type": "integer", "default": 1000, "minimum": 1, "description": "Vectors per batch"}, "index_path": {"type": "string", "default": "./data/faiss_index", "description": "Path to save index"}, "overwrite": {"type": "boolean", "default": False, "description": "Overwrite existing index"}}}, "input_ports": [{"name": "embeddings", "type": "embedding_list"}], "output_ports": [{"name": "index", "type": "vector_index"}]},
    {"type": "milvus_indexer", "category": "indexer", "name": "Milvus Indexer", "description": "Index vectors in Milvus. DiskANN for >100M vectors", "config_schema": {"type": "object", "properties": {"uri": {"type": "string", "default": "http://localhost:19530", "description": "Milvus server URI"}, "collection_name": {"type": "string", "default": "rrag_default", "description": "Collection name"}, "index_type": {"type": "string", "enum": ["hnsw", "ivf_flat", "ivf_sq8", "ivf_pq", "diskann"], "default": "hnsw", "description": "Milvus index type"}, "distance_metric": {"type": "string", "enum": ["cosine", "l2", "inner_product"], "default": "cosine", "description": "Distance metric"}, "dimension": {"type": "integer", "default": 1536, "minimum": 1, "description": "Embedding dimension"}, "hnsw_m": {"type": "integer", "default": 16, "minimum": 4, "maximum": 64, "description": "HNSW M parameter"}, "hnsw_ef_construction": {"type": "integer", "default": 128, "minimum": 16, "maximum": 512, "description": "HNSW efConstruction"}}}, "input_ports": [{"name": "embeddings", "type": "embedding_list"}], "output_ports": [{"name": "index", "type": "vector_index"}]},
    {"type": "dense_retriever", "category": "retriever", "name": "Dense Retriever", "description": "Dense vector similarity search using FAISS/Milvus index", "config_schema": {"type": "object", "properties": {"index_path": {"type": "string", "default": "./data/faiss_index", "description": "Vector index path"}, "top_k": {"type": "integer", "default": 20, "minimum": 1, "maximum": 1000, "description": "Documents to retrieve"}, "embedding_model": {"type": "string", "default": "openai", "enum": ["openai", "e5", "sentence_transformer", "bge_m3", "cohere", "jina", "nomic", "voyage"], "description": "Embedding model for query encoding"}, "query_prefix": {"type": "string", "default": "", "description": "Query embedding prefix"}, "score_threshold": {"type": "number", "default": 0.0, "minimum": 0.0, "maximum": 1.0, "description": "Minimum similarity score"}, "use_mmr": {"type": "boolean", "default": False, "description": "Apply MMR for diversity"}, "mmr_lambda": {"type": "number", "default": 0.5, "minimum": 0.0, "maximum": 1.0, "description": "MMR relevance-diversity trade-off"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "hybrid_retriever", "category": "retriever", "name": "Hybrid Retriever", "description": "Combines dense vector and BM25 keyword retrieval. +26-31% NDCG vs dense-only", "config_schema": {"type": "object", "properties": {"top_k": {"type": "integer", "default": 20, "minimum": 1, "maximum": 1000, "description": "Documents to retrieve"}, "alpha": {"type": "number", "default": 0.6, "minimum": 0.0, "maximum": 1.0, "description": "Dense weight (1.0=all dense, 0.0=all sparse). Optimal: 0.6-0.7"}, "fusion_method": {"type": "string", "enum": ["rrf", "weighted_sum", "convex_combination"], "default": "rrf", "description": "Score fusion method"}, "rrf_k": {"type": "integer", "default": 60, "minimum": 1, "description": "RRF smoothing constant"}, "bm25_k1": {"type": "number", "default": 1.2, "minimum": 0.0, "maximum": 3.0, "description": "BM25 term frequency saturation"}, "bm25_b": {"type": "number", "default": 0.75, "minimum": 0.0, "maximum": 1.0, "description": "BM25 length normalization"}, "embedding_model": {"type": "string", "default": "openai", "description": "Embedding model for dense component"}, "normalize_scores": {"type": "boolean", "default": True, "description": "Normalize scores before fusion"}, "use_mmr": {"type": "boolean", "default": False, "description": "Apply MMR for diversity"}, "mmr_lambda": {"type": "number", "default": 0.5, "minimum": 0.0, "maximum": 1.0, "description": "MMR trade-off"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "embeddings", "type": "embedding_list"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "graph_retriever", "category": "retriever", "name": "Graph Retriever", "description": "Knowledge graph-based retrieval via entity traversal and community summaries (GraphRAG/HippoRAG)", "config_schema": {"type": "object", "properties": {"top_k": {"type": "integer", "default": 20, "minimum": 1, "description": "Documents to retrieve"}, "graph_uri": {"type": "string", "default": "bolt://localhost:7687", "description": "Neo4j URI"}, "graph_search_depth": {"type": "integer", "default": 2, "minimum": 1, "maximum": 5, "description": "Max traversal hops"}, "community_level": {"type": "integer", "default": 0, "minimum": 0, "description": "Community hierarchy level (0=leaf)"}, "embedding_model": {"type": "string", "default": "openai", "description": "Embedding model for entity matching"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "web_retriever", "category": "retriever", "name": "Web Search Retriever", "description": "Search the web for relevant information", "config_schema": {"type": "object", "properties": {"search_engine": {"type": "string", "enum": ["duckduckgo", "serper", "tavily", "brave"], "default": "duckduckgo", "description": "Web search provider"}, "max_results": {"type": "integer", "default": 5, "minimum": 1, "description": "Maximum results"}, "top_k": {"type": "integer", "default": 5, "minimum": 1, "description": "Documents to return"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "cross_encoder_reranker", "category": "reranker", "name": "Cross-Encoder Reranker", "description": "Cross-encoder reranking. BGE-reranker-v2-m3: best open-source multilingual", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "BAAI/bge-reranker-v2-m3", "description": "Cross-encoder model"}, "top_k": {"type": "integer", "default": 10, "minimum": 1, "description": "Documents to return"}, "score_threshold": {"type": "number", "default": 0.0, "minimum": -1.0, "maximum": 1.0, "description": "Minimum score to keep"}, "max_length": {"type": "integer", "default": 512, "minimum": 128, "maximum": 8192, "description": "Max tokens per pair"}, "batch_size": {"type": "integer", "default": 32, "minimum": 1, "description": "Pairs per batch"}, "device": {"type": "string", "enum": ["cpu", "cuda", "mps", "auto"], "default": "auto", "description": "Compute device"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "cohere_reranker", "category": "reranker", "name": "Cohere Reranker", "description": "Cohere Rerank 4 Pro: robust multilingual API reranker", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "rerank-v3.5", "description": "Cohere reranker model"}, "top_k": {"type": "integer", "default": 10, "minimum": 1, "description": "Documents to return"}, "max_tokens_per_doc": {"type": "integer", "default": 4096, "minimum": 128, "description": "Max tokens per document"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "jina_reranker", "category": "reranker", "name": "Jina Reranker", "description": "Jina-Reranker-v3: highest BEIR nDCG@10 (61.94). Listwise reranking (arXiv:2509.25085)", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "jinaai/jina-reranker-v2-base-multilingual", "description": "Jina reranker model"}, "top_k": {"type": "integer", "default": 10, "minimum": 1, "description": "Documents to return"}, "device": {"type": "string", "enum": ["cpu", "cuda", "mps", "auto"], "default": "auto", "description": "Compute device"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "llm_listwise_reranker", "category": "reranker", "name": "LLM Listwise Reranker", "description": "RankGPT/RankZephyr-style LLM reranking. Best generalization (arXiv:2312.02724)", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for reranking"}, "top_k": {"type": "integer", "default": 10, "minimum": 1, "description": "Documents to return"}, "window_size": {"type": "integer", "default": 20, "minimum": 5, "description": "Documents per sliding window"}, "step_size": {"type": "integer", "default": 10, "minimum": 1, "description": "Sliding window stride"}, "num_passes": {"type": "integer", "default": 1, "minimum": 1, "maximum": 3, "description": "Number of reranking passes"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "llm_generator", "category": "generator", "name": "LLM Generator", "description": "RAG answer generation with citations and context management", "config_schema": {"type": "object", "properties": {"model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM model"}, "provider": {"type": "string", "enum": ["openai", "anthropic", "local", "groq", "together"], "default": "openai", "description": "LLM provider"}, "temperature": {"type": "number", "default": 0.2, "minimum": 0.0, "maximum": 2.0, "description": "Sampling temperature. Use 0.1-0.3 for factual RAG"}, "top_p": {"type": "number", "default": 0.9, "minimum": 0.0, "maximum": 1.0, "description": "Nucleus sampling"}, "max_tokens": {"type": "integer", "default": 2048, "minimum": 1, "maximum": 128000, "description": "Maximum output tokens"}, "frequency_penalty": {"type": "number", "default": 0.1, "minimum": -2.0, "maximum": 2.0, "description": "Penalize repeated tokens", "ui_advanced": True}, "presence_penalty": {"type": "number", "default": 0.0, "minimum": -2.0, "maximum": 2.0, "description": "Penalize tokens already present", "ui_advanced": True}, "system_prompt": {"type": "string", "default": "You are a helpful assistant. Answer based on the provided context. If the context doesn't contain the answer, say so.", "description": "System prompt", "ui_widget": "textarea"}, "citation_mode": {"type": "string", "enum": ["none", "inline", "footnote", "structured", "quote_grounding"], "default": "inline", "description": "Citation handling in response"}, "context_ordering": {"type": "string", "enum": ["relevance_first", "recency_first", "sandwich", "random"], "default": "relevance_first", "description": "Order of retrieved documents in prompt"}, "context_max_tokens": {"type": "integer", "default": 8000, "minimum": 100, "description": "Max tokens for context"}, "enable_cot": {"type": "boolean", "default": False, "description": "Enable chain-of-thought reasoning"}, "response_format": {"type": "string", "enum": ["text", "json", "markdown"], "default": "text", "description": "Response format"}, "stream": {"type": "boolean", "default": True, "description": "Stream response"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}], "output_ports": [{"name": "response", "type": "string"}]},
    {"type": "kv_store", "category": "storage", "name": "Key-Value Store", "description": "Key-value storage in Redis for caching and metadata", "config_schema": {"type": "object", "properties": {"kv_backend": {"type": "string", "enum": ["redis", "memcached", "dynamodb"], "default": "redis", "description": "KV store backend"}, "key_prefix": {"type": "string", "default": "rrag:", "description": "Key prefix for namespacing"}, "ttl_seconds": {"type": "integer", "default": 0, "minimum": 0, "description": "TTL in seconds (0=no expiry)"}, "uri": {"type": "string", "default": "", "description": "Connection URI"}, "batch_size": {"type": "integer", "default": 100, "minimum": 1, "description": "Items per batch"}}}, "input_ports": [{"name": "data", "type": "any"}], "output_ports": [{"name": "stored", "type": "any"}]},
    {"type": "graph_store", "category": "storage", "name": "Graph Store (Neo4j)", "description": "Persist knowledge graph to Neo4j database", "config_schema": {"type": "object", "properties": {"graph_backend": {"type": "string", "enum": ["neo4j", "neptune", "memgraph"], "default": "neo4j", "description": "Graph database backend"}, "uri": {"type": "string", "default": "bolt://localhost:7687", "description": "Graph database URI"}, "username": {"type": "string", "default": "neo4j", "description": "Username"}, "password": {"type": "string", "default": "", "description": "Password", "ui_widget": "password"}, "batch_size": {"type": "integer", "default": 100, "minimum": 1, "description": "Items per batch"}}}, "input_ports": [{"name": "graph", "type": "knowledge_graph"}], "output_ports": [{"name": "stored", "type": "knowledge_graph"}]},
    {"type": "vector_store", "category": "storage", "name": "Vector Store", "description": "Persist embeddings to vector database", "config_schema": {"type": "object", "properties": {"vector_backend": {"type": "string", "enum": ["faiss", "milvus", "pgvector", "qdrant", "chroma"], "default": "faiss", "description": "Vector storage backend"}, "collection_name": {"type": "string", "default": "rrag_default", "description": "Collection name"}, "uri": {"type": "string", "default": "", "description": "Connection URI"}, "batch_size": {"type": "integer", "default": 1000, "minimum": 1, "description": "Vectors per batch"}, "upsert": {"type": "boolean", "default": True, "description": "Insert or update existing"}}}, "input_ports": [{"name": "embeddings", "type": "embedding_list"}], "output_ports": [{"name": "stored", "type": "any"}]},
    {"type": "query_router", "category": "agent", "name": "Query Router", "description": "Routes queries to optimal retrieval strategy. Adaptive routing (CRAG/Adaptive-RAG)", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for routing decisions"}, "routing_mode": {"type": "string", "enum": ["adaptive", "rule_based", "llm_classifier"], "default": "adaptive", "description": "Routing approach"}, "available_strategies": {"type": "array", "items": {"type": "string"}, "default": ["dense", "hybrid", "graph", "web"], "description": "Available retrieval strategies"}, "confidence_upper_threshold": {"type": "number", "default": 0.7, "minimum": 0.0, "maximum": 1.0, "description": "Above = direct retrieval"}, "confidence_lower_threshold": {"type": "number", "default": 0.3, "minimum": 0.0, "maximum": 1.0, "description": "Below = web search fallback"}, "fallback_strategy": {"type": "string", "default": "web_search", "description": "Fallback on low confidence"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "routing", "type": "object"}, {"name": "query", "type": "string"}]},
    {"type": "reflection_agent", "category": "agent", "name": "Reflection Agent", "description": "Evaluates response quality and triggers retry. Self-RAG / RAG-HAT style", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for evaluation"}, "min_quality_score": {"type": "number", "default": 6.0, "minimum": 0.0, "maximum": 10.0, "description": "Minimum quality score (1-10)"}, "max_retries": {"type": "integer", "default": 3, "minimum": 0, "description": "Max retry attempts"}, "critique_dimensions": {"type": "array", "items": {"type": "string"}, "default": ["faithfulness", "relevance", "completeness", "coherence"], "description": "Evaluation dimensions"}, "hallucination_detection": {"type": "string", "enum": ["llm_judge", "nli_model", "self_consistency", "none"], "default": "llm_judge", "description": "Hallucination detection method"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "response", "type": "string"}], "output_ports": [{"name": "score", "type": "number"}, {"name": "feedback", "type": "string"}]},
    {"type": "memory_agent", "category": "agent", "name": "Conversation Memory", "description": "Manages conversation context and history. A-Mem / MemR3 style", "config_schema": {"type": "object", "properties": {"memory_type": {"type": "string", "enum": ["conversation", "episodic", "semantic", "working"], "default": "conversation", "description": "Memory architecture"}, "max_history_turns": {"type": "integer", "default": 20, "minimum": 1, "description": "Max conversation turns to keep"}, "summarization_enabled": {"type": "boolean", "default": True, "description": "Summarize old turns to save tokens"}, "importance_scoring": {"type": "boolean", "default": True, "description": "Score items by importance for retention"}, "decay_rate": {"type": "number", "default": 0.95, "minimum": 0.0, "maximum": 1.0, "description": "Memory decay factor"}, "max_memory_tokens": {"type": "integer", "default": 4000, "minimum": 100, "description": "Max tokens for memory context"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "response", "type": "string"}], "output_ports": [{"name": "context", "type": "string"}]},
    {"type": "tool_use_agent", "category": "agent", "name": "Tool Use Agent", "description": "Executes external tools (APIs, calculators, databases) based on query needs", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for tool selection"}, "available_tools": {"type": "array", "items": {"type": "string"}, "default": [], "description": "Available tool names"}, "max_tool_calls": {"type": "integer", "default": 5, "minimum": 1, "description": "Max tool calls per turn"}, "tool_selection_mode": {"type": "string", "enum": ["llm", "rule_based"], "default": "llm", "description": "How tools are selected"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "result", "type": "object"}]},
    {"type": "orchestrator_agent", "category": "agent", "name": "Orchestrator", "description": "Coordinates multi-agent workflows with iteration and convergence", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for orchestration"}, "max_iterations": {"type": "integer", "default": 10, "minimum": 1, "description": "Max orchestration iterations"}, "convergence_threshold": {"type": "number", "default": 0.8, "minimum": 0.0, "maximum": 1.0, "description": "Quality threshold for convergence"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "result", "type": "object"}]},
    {"type": "corag_planner", "category": "planner", "name": "CoRAG Planner", "description": "Multi-hop retrieval planning with rejection sampling (arXiv:2501.14342)", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for planning"}, "strategy": {"type": "string", "enum": ["greedy", "best_of_n", "beam", "tree_search"], "default": "greedy", "description": "Search strategy"}, "max_hops": {"type": "integer", "default": 3, "minimum": 1, "maximum": 10, "description": "Maximum retrieval hops"}, "n_samples": {"type": "integer", "default": 5, "minimum": 1, "description": "Samples for best_of_n"}, "beam_width": {"type": "integer", "default": 3, "minimum": 1, "description": "Beam width", "ui_advanced": True}, "reformulation_enabled": {"type": "boolean", "default": True, "description": "Allow query reformulation between hops"}, "confidence_threshold": {"type": "number", "default": 0.6, "minimum": 0.0, "maximum": 1.0, "description": "Min confidence to accept"}, "backtracking_enabled": {"type": "boolean", "default": True, "description": "Allow backtracking on contradictions"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "plan", "type": "object"}]},
    {"type": "mcts_planner", "category": "planner", "name": "MCTS Planner", "description": "Monte Carlo Tree Search for RAG planning. +20% improvement (arXiv:2503.20757)", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for planning"}, "mcts_simulations": {"type": "integer", "default": 100, "minimum": 10, "description": "MCTS simulation budget"}, "mcts_exploration_constant": {"type": "number", "default": 1.414, "minimum": 0.0, "description": "UCT exploration constant"}, "max_depth": {"type": "integer", "default": 5, "minimum": 1, "description": "Maximum tree depth"}, "max_hops": {"type": "integer", "default": 3, "minimum": 1, "maximum": 10, "description": "Maximum retrieval hops"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "plan", "type": "object"}]},
    {"type": "kag_planner", "category": "planner", "name": "KAG Planner", "description": "Decomposes queries into logical-form operator DAG for KAG execution", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for planning"}, "operators": {"type": "array", "items": {"type": "string"}, "default": ["kg_retrieval", "text_retrieval", "math", "deduce"], "description": "Available operators"}, "max_reasoning_steps": {"type": "integer", "default": 5, "minimum": 1, "maximum": 20, "description": "Max reasoning steps"}, "plan_format": {"type": "string", "enum": ["sequential", "dag", "tree"], "default": "dag", "description": "Output plan structure"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "plan", "type": "object"}]},
    {"type": "self_cognition_gate", "category": "agent", "name": "Self-Cognition Gate", "description": "KAG-inspired: check if LLM already knows the answer before retrieval. Skips 30-40% of queries", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for confidence estimation"}, "confidence_threshold": {"type": "number", "default": 0.7, "minimum": 0.0, "maximum": 1.0, "description": "Above this threshold, skip retrieval and answer directly"}, "estimation_method": {"type": "string", "enum": ["self_probe", "logprob", "consistency"], "default": "self_probe", "description": "How to estimate knowledge confidence"}, "consistency_samples": {"type": "integer", "default": 3, "minimum": 2, "maximum": 10, "description": "Samples for consistency-based estimation", "ui_advanced": True}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "decision", "type": "object"}, {"name": "direct_answer", "type": "string"}]},
    {"type": "deep_rag_agent", "category": "agent", "name": "Deep RAG Agent", "description": "Interleaves retrieval within chain-of-thought. Each reasoning step can trigger retrieval (DeepRAG/AirRAG)", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for reasoning"}, "max_reasoning_steps": {"type": "integer", "default": 8, "minimum": 1, "maximum": 20, "description": "Maximum reasoning steps"}, "retrieval_trigger": {"type": "string", "enum": ["llm_decision", "confidence_drop", "always"], "default": "llm_decision", "description": "When to trigger mid-reasoning retrieval"}, "max_retrievals_per_chain": {"type": "integer", "default": 3, "minimum": 1, "maximum": 10, "description": "Max retrieval calls per reasoning chain"}, "early_stop_confidence": {"type": "number", "default": 0.85, "minimum": 0.0, "maximum": 1.0, "description": "Stop reasoning early if confidence exceeds this"}, "show_reasoning_trace": {"type": "boolean", "default": True, "description": "Include reasoning trace in output"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}], "output_ports": [{"name": "response", "type": "string"}, {"name": "trace", "type": "object"}]},
    {"type": "adaptive_retrieval_controller", "category": "agent", "name": "Adaptive Retrieval Controller", "description": "Stop-RAG: dynamically decides retrieval depth. 40% fewer retrievals with same quality", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for sufficiency estimation"}, "sufficiency_method": {"type": "string", "enum": ["llm_judge", "nli_check", "token_coverage", "embedding_saturation"], "default": "llm_judge", "description": "Method to assess context sufficiency"}, "sufficiency_threshold": {"type": "number", "default": 0.75, "minimum": 0.0, "maximum": 1.0, "description": "Threshold to stop retrieving"}, "max_retrieval_rounds": {"type": "integer", "default": 5, "minimum": 1, "maximum": 20, "description": "Hard limit on retrieval rounds"}, "nli_filter_enabled": {"type": "boolean", "default": False, "description": "Filter contradicting documents using NLI"}, "dedup_retrieved": {"type": "boolean", "default": True, "description": "Deduplicate across retrieval rounds"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}], "output_ports": [{"name": "documents", "type": "document_list"}, {"name": "sufficient", "type": "boolean"}]},
    {"type": "streaming_retriever", "category": "retriever", "name": "Streaming Retriever", "description": "RAPID-style: streams retrieved docs progressively as they arrive. 50% latency reduction", "config_schema": {"type": "object", "properties": {"retriever_type": {"type": "string", "enum": ["dense", "hybrid", "graph"], "default": "hybrid", "description": "Underlying retriever"}, "top_k": {"type": "integer", "default": 20, "minimum": 1, "maximum": 1000, "description": "Total documents"}, "stream_batch_size": {"type": "integer", "default": 5, "minimum": 1, "maximum": 50, "description": "Documents per stream batch"}, "early_generation_threshold": {"type": "integer", "default": 3, "minimum": 1, "description": "Start generation after this many documents arrive"}, "timeout_ms": {"type": "integer", "default": 5000, "minimum": 100, "maximum": 30000, "description": "Max wait per batch in milliseconds"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "table_retriever", "category": "retriever", "name": "Table Retriever", "description": "TableRAG: retrieves from structured tabular data using schema matching and cell retrieval", "config_schema": {"type": "object", "properties": {"top_k": {"type": "integer", "default": 5, "minimum": 1, "maximum": 100, "description": "Tables to retrieve"}, "schema_matching": {"type": "string", "enum": ["embedding", "llm", "keyword"], "default": "embedding", "description": "How to match query to table schemas"}, "cell_retrieval_enabled": {"type": "boolean", "default": True, "description": "Enable fine-grained cell-level retrieval"}, "sql_generation_enabled": {"type": "boolean", "default": False, "description": "Generate and execute SQL queries"}, "sql_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for SQL generation (if enabled)"}, "max_rows_per_table": {"type": "integer", "default": 100, "minimum": 1, "description": "Max rows to return per table"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "gfm_retriever", "category": "retriever", "name": "GFM Retriever", "description": "Graph Foundation Model retriever: pre-trained GNN for cross-domain graph-based retrieval (GFM-RAG)", "config_schema": {"type": "object", "properties": {"top_k": {"type": "integer", "default": 20, "minimum": 1, "description": "Documents to retrieve"}, "gfm_model_path": {"type": "string", "default": "", "description": "Path to pre-trained GFM model checkpoint"}, "graph_uri": {"type": "string", "default": "bolt://localhost:7687", "description": "Graph database URI"}, "reasoning_depth": {"type": "integer", "default": 3, "minimum": 1, "maximum": 10, "description": "GNN message passing depth"}, "entity_embedding_dim": {"type": "integer", "default": 256, "minimum": 64, "description": "Entity embedding dimension"}}}, "input_ports": [{"name": "query", "type": "string"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "context_compressor", "category": "reranker", "name": "Context Compressor", "description": "Post-retrieval compression: 50-70% token reduction with <2% quality loss (CompactRAG/LinearRAG)", "config_schema": {"type": "object", "properties": {"compression_method": {"type": "string", "enum": ["extractive", "abstractive", "token_pruning", "sentence_selection"], "default": "extractive", "description": "Compression approach"}, "target_ratio": {"type": "number", "default": 0.4, "minimum": 0.1, "maximum": 1.0, "description": "Target compression ratio (0.4 = keep 40% of tokens)"}, "llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for abstractive compression"}, "preserve_structure": {"type": "boolean", "default": True, "description": "Preserve document structure (headers, lists) during compression"}, "query_focused": {"type": "boolean", "default": True, "description": "Focus compression on query-relevant content"}, "min_output_tokens": {"type": "integer", "default": 100, "minimum": 10, "description": "Minimum tokens to keep per document"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}], "output_ports": [{"name": "documents", "type": "document_list"}]},
    {"type": "speculative_generator", "category": "generator", "name": "Speculative Generator", "description": "Draft with small model, verify with large model. 2-3x faster generation (Speculative RAG)", "config_schema": {"type": "object", "properties": {"draft_model": {"type": "string", "default": "gpt-4o-mini", "description": "Small model for drafting"}, "verify_model": {"type": "string", "default": "gpt-4o", "description": "Large model for verification"}, "provider": {"type": "string", "enum": ["openai", "anthropic", "local", "groq", "together"], "default": "openai", "description": "LLM provider"}, "num_drafts": {"type": "integer", "default": 3, "minimum": 1, "maximum": 5, "description": "Parallel draft candidates"}, "context_split_strategy": {"type": "string", "enum": ["random_subset", "ranked_subset", "round_robin"], "default": "ranked_subset", "description": "How to split context across draft candidates"}, "temperature": {"type": "number", "default": 0.3, "minimum": 0.0, "maximum": 2.0, "description": "Drafting temperature"}, "max_tokens": {"type": "integer", "default": 2048, "minimum": 1, "maximum": 128000, "description": "Max output tokens"}, "stream": {"type": "boolean", "default": True, "description": "Stream response"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}], "output_ports": [{"name": "response", "type": "string"}]},
    {"type": "vision_generator", "category": "generator", "name": "Vision Generator", "description": "Generate answers from document images using vision-language models (VisRAG pattern)", "config_schema": {"type": "object", "properties": {"model": {"type": "string", "default": "gpt-4o", "description": "Vision-language model"}, "provider": {"type": "string", "enum": ["openai", "anthropic", "local"], "default": "openai", "description": "LLM provider"}, "max_images": {"type": "integer", "default": 5, "minimum": 1, "maximum": 20, "description": "Maximum document images to include"}, "image_resolution": {"type": "string", "enum": ["low", "medium", "high", "auto"], "default": "auto", "description": "Image resolution for API"}, "temperature": {"type": "number", "default": 0.2, "minimum": 0.0, "maximum": 2.0, "description": "Sampling temperature"}, "max_tokens": {"type": "integer", "default": 2048, "minimum": 1, "maximum": 128000, "description": "Max output tokens"}, "system_prompt": {"type": "string", "default": "Analyze the provided document images and answer the question. Reference specific visual elements when relevant.", "description": "System prompt", "ui_widget": "textarea"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "images", "type": "image_list"}], "output_ports": [{"name": "response", "type": "string"}]},
    {"type": "multimodal_embedder", "category": "embedder", "name": "Multimodal Embedder", "description": "Embed document pages as images using vision encoders. Handles charts, diagrams, layouts (ColPali/VisRAG)", "config_schema": {"type": "object", "properties": {"model_name": {"type": "string", "default": "vidore/colpali-v1.3", "description": "Vision-language embedding model"}, "embedding_mode": {"type": "string", "enum": ["late_interaction", "dense", "hybrid_text_vision"], "default": "late_interaction", "description": "Embedding approach"}, "image_resolution": {"type": "integer", "default": 448, "minimum": 224, "maximum": 1024, "description": "Image resolution for encoding"}, "batch_size": {"type": "integer", "default": 8, "minimum": 1, "description": "Pages per batch"}, "device": {"type": "string", "enum": ["cpu", "cuda", "mps", "auto"], "default": "auto", "description": "Compute device"}, "max_pages": {"type": "integer", "default": 100, "minimum": 1, "description": "Max pages to embed per document"}}}, "input_ports": [{"name": "documents", "type": "document_list"}], "output_ports": [{"name": "embeddings", "type": "embedding_list"}]},
    {"type": "rag_evaluator", "category": "agent", "name": "RAG Evaluator", "description": "Built-in evaluation and tracing. Measures faithfulness, relevance, and retrieval quality (RAGAS/FaithJudge)", "config_schema": {"type": "object", "properties": {"llm_model": {"type": "string", "default": "gpt-4o-mini", "description": "LLM for evaluation"}, "metrics": {"type": "array", "items": {"type": "string", "enum": ["faithfulness", "answer_relevance", "context_precision", "context_recall", "noise_robustness", "hallucination_rate"]}, "default": ["faithfulness", "answer_relevance", "context_precision"], "description": "Evaluation metrics to compute"}, "evaluation_mode": {"type": "string", "enum": ["inline", "post_hoc", "continuous"], "default": "post_hoc", "description": "When to run evaluation"}, "trace_enabled": {"type": "boolean", "default": True, "description": "Enable per-component tracing (latency, tokens, quality)"}, "fail_threshold": {"type": "number", "default": 0.3, "minimum": 0.0, "maximum": 1.0, "description": "Below this score, flag response as low quality"}, "log_traces": {"type": "boolean", "default": True, "description": "Persist traces for analytics"}}}, "input_ports": [{"name": "query", "type": "string"}, {"name": "documents", "type": "document_list"}, {"name": "response", "type": "string"}], "output_ports": [{"name": "scores", "type": "object"}, {"name": "trace", "type": "object"}]},
]


async def get_all_components(db: AsyncSession, *, redis=None) -> list[Component]:
    """Return all registered component definitions."""
    if redis:
        from ..cache import cache_get, cache_set, TTL_STATIC
        cached = cache_get(redis, "comp", "_global", "list")
        if cached is not None:
            return cached
    result = await db.execute(select(Component).order_by(Component.category, Component.name))
    rows = list(result.scalars().all())
    if redis:
        from ..cache import cache_set, TTL_STATIC
        data = [{"type": c.type, "category": c.category, "name": c.name,
                 "description": c.description, "config_schema": c.config_schema,
                 "input_ports": c.input_ports, "output_ports": c.output_ports,
                 "source": getattr(c, "source", "seed"),
                 "is_composite": getattr(c, "is_composite", False),
                 "steps": getattr(c, "steps", None),
                 "workspace_id": getattr(c, "workspace_id", "_global"),
                 } for c in rows]
        cache_set(redis, "comp", "_global", data, suffix="list", ttl=TTL_STATIC)
    return rows


async def get_component(db: AsyncSession, component_type: str, *, redis=None) -> Component | None:
    """Return a single component definition by type, or None if not found."""
    if redis:
        from ..cache import cache_get, cache_set, TTL_STATIC
        cached = cache_get(redis, "comp", "_global", component_type)
        if cached is not None:
            return cached
    result = await db.execute(select(Component).where(Component.type == component_type))
    comp = result.scalar_one_or_none()
    if comp and redis:
        from ..cache import cache_set, TTL_STATIC
        data = {"type": comp.type, "category": comp.category, "name": comp.name,
                "description": comp.description, "config_schema": comp.config_schema,
                "input_ports": comp.input_ports, "output_ports": comp.output_ports,
                "source": getattr(comp, "source", "seed"),
                "is_composite": getattr(comp, "is_composite", False),
                "steps": getattr(comp, "steps", None),
                "workspace_id": getattr(comp, "workspace_id", "_global"),
                }
        cache_set(redis, "comp", "_global", data, suffix=component_type, ttl=TTL_STATIC)
    return comp


async def get_components_by_category(db: AsyncSession, category: str) -> list[Component]:
    """Return all components for a given category."""
    result = await db.execute(select(Component).where(Component.category == category))
    return list(result.scalars().all())


async def upsert_custom_component(
    db: AsyncSession,
    *,
    type: str,
    category: str,
    name: str,
    description: str = "",
    config_schema: dict | None = None,
    input_ports: list | None = None,
    output_ports: list | None = None,
    is_composite: bool = False,
    steps: list | None = None,
    source: str = "custom",
    workspace_id: str,
    file_path: str | None = None,
    file_hash: str | None = None,
) -> Component:
    """Insert or update a custom component."""
    stmt = select(Component).where(
        Component.type == type, Component.workspace_id == workspace_id
    )
    result = await db.execute(stmt)
    existing = result.scalar_one_or_none()

    if existing:
        existing.category = category
        existing.name = name
        existing.description = description
        existing.config_schema = config_schema or {}
        existing.input_ports = input_ports or []
        existing.output_ports = output_ports or []
        existing.is_composite = is_composite
        existing.steps = steps
        existing.source = source
        existing.file_path = file_path
        existing.file_hash = file_hash
        await db.commit()
        await db.refresh(existing)
        return existing

    comp = Component(
        type=type,
        category=category,
        name=name,
        description=description,
        config_schema=config_schema or {},
        input_ports=input_ports or [],
        output_ports=output_ports or [],
        is_composite=is_composite,
        steps=steps,
        source=source,
        workspace_id=workspace_id,
        file_path=file_path,
        file_hash=file_hash,
    )
    db.add(comp)
    await db.commit()
    await db.refresh(comp)
    return comp


async def delete_component(
    db: AsyncSession, component_type: str, workspace_id: str, *, redis=None
) -> bool:
    """Delete a custom component. Returns True if deleted."""
    stmt = select(Component).where(
        Component.type == component_type,
        Component.workspace_id == workspace_id,
        Component.source == "custom",
    )
    result = await db.execute(stmt)
    comp = result.scalar_one_or_none()
    if comp:
        await db.delete(comp)
        await db.commit()
        if redis:
            await redis.delete("components:all")
        return True
    return False


async def get_seed_component(db: AsyncSession, component_type: str) -> Component | None:
    """Check if a seed component exists with this type."""
    stmt = select(Component).where(
        Component.type == component_type,
        Component.workspace_id == "_global",
    )
    result = await db.execute(stmt)
    return result.scalar_one_or_none()
